language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t mpq1990/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mpq1990/docker-react npm run test -- --coverage
